{
    "_activityBlocks": {
        "calculateMaxWithExceptionEverySecondRun2": {
            "mode": "ACTIVITY_BLOCK_RERUN",
            "flowConfigPath": "test-config.yml",
            "_activities": {
                "calculateMaxWithExceptionEverySecondRun2-activity1": {
                    "action": "REUSE",
                    "status": "SUCCESS",
                    "run_nbr": 3
                },
                "calculateMaxWithExceptionEverySecondRun2-activity2": {
                    "action": "REUSE",
                    "status": "SUCCESS",
                    "max": 5
                },
                "calculateMaxWithExceptionEverySecondRun2-activity3": {
                    "action": "REUSE",
                    "status": "SUCCESS",
                    "max": 5
                },
                "calculateMaxWithExceptionEverySecondRun2-exceptionEverySecondRun": {
                    "action": "RUN",
                    "status": "SUCCESS",
                    "max": 5
                },
                "calculateMaxWithExceptionEverySecondRun2-activity5": {
                    "action": "RUN",
                    "status": "SUCCESS",
                    "max": 5
                }
            },
            "action": "RUN",
            "status": "SUCCESS",
            "run_nbr": 3,
            "max": 5,
            "activityBlockStatus": "SUCCESS"
        }
    },
    "mode": "ACTIVITY_BLOCK_RERUN",
    "flowConfigPath": "test-config.yml",
    "action": "RUN",
    "status": "SUCCESS",
    "run_nbr": 3,
    "max": 5,
    "activityBlockStatus": "SUCCESS",
    "exceptions": [
        {
            "message": "This is a planned exception for an odd run number.",
            "class": "Exception",
            "description": "Exception caught during activity run: Exception: This is a planned exception for an odd run number.",
            "type": "ACTIVITY",
            "state": "BEFORE_ACTIVITY_RUN",
            "stackTrace": [
                "Traceback (most recent call last):",
                "  File \"C:\\github\\widerscale\\autor\\autor\\framework\\activity_runner.py\", line 126, in _run",
                "    self._data.activity.run()",
                "  File \"C:\\github\\widerscale\\autor\\tests\\test_activities\\activities.py\", line 107, in run",
                "    raise Exception(\"This is a planned exception for an odd run number.\")",
                "Exception: This is a planned exception for an odd run number."
            ],
            "custom": {
                "activityId": "calculateMaxWithExceptionEverySecondRun2-exceptionEverySecondRun",
                "activityStatus": "ERROR"
            }
        }
    ]
}